"""KoPy transliteration dictionary.

KoPy deliberately keeps Python grammar intact. Only exact NAME tokens listed here
are converted before CPython compiles the source.
"""

WORDS: dict[str, str] = {
    # Python keywords / soft-keyword-adjacent learning words
    "펄스": "False",
    "논": "None",
    "트루": "True",
    "앤드": "and",
    "애즈": "as",
    "어설트": "assert",
    "어싱크": "async",
    "어웨이트": "await",
    "브레이크": "break",
    "클래스": "class",
    "컨티뉴": "continue",
    "데프": "def",
    "델": "del",
    "엘리프": "elif",
    "엘스": "else",
    "익셉트": "except",
    "파이널리": "finally",
    "포": "for",
    "프롬": "from",
    "글로벌": "global",
    "이프": "if",
    "임포트": "import",
    "인": "in",
    "이즈": "is",
    "람다": "lambda",
    "논로컬": "nonlocal",
    "낫": "not",
    "오어": "or",
    "패스": "pass",
    "레이즈": "raise",
    "리턴": "return",
    "트라이": "try",
    "와일": "while",
    "위드": "with",
    "일드": "yield",

    # Frequently used built-ins
    "프린트": "print",
    "인풋": "input",
    "인트": "int",
    "플로트": "float",
    "스트링": "str",
    "불": "bool",
    "바이트": "bytes",
    "리스트": "list",
    "딕트": "dict",
    "튜플": "tuple",
    "셋": "set",
    "렌": "len",
    "레인지": "range",
    "오픈": "open",
    "타입": "type",
    "썸": "sum",
    "민": "min",
    "맥스": "max",
    "앱스": "abs",
    "라운드": "round",
    "소티드": "sorted",
    "이뉴머레이트": "enumerate",
    "집": "zip",
    "맵": "map",
    "필터": "filter",
    "올": "all",
    "애니": "any",
    "아이디": "id",
    "헬프": "help",
    "디르": "dir",
    "리버스드": "reversed",
    "슬라이스": "slice",
    "슈퍼": "super",
    "오브젝트": "object",
    "아이시인스턴스": "isinstance",
    "아이서브클래스": "issubclass",
    "콜러블": "callable",
    "크르": "chr",
    "오드": "ord",
    "빈": "bin",
    "옥트": "oct",
    "헥스": "hex",
    "파우": "pow",
}

ENGLISH_TARGETS: frozenset[str] = frozenset(WORDS.values())
